# Replication Controller for webapp
apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp1
spec:
  replicas: 2
  selector:
    app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - image: myjenkinsacr.azurecr.io/java-web-app-docker:83
        name: webapp1
        ports:
        - containerPort: 8080  
---
# Node Port Service For webapp
apiVersion: v1
kind: Service
metadata:
  name: webapp1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webapp1
