# Replication Controller for webapp
apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: myjenkinsacr.azurecr.io/java-web-app-docker
        name: webapp
        ports:
        - containerPort: 8080  
---
# Node Port Service For webapp
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webapp
